on: push
name: Publish
jobs:
  Deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Setup-Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'
    - name: Build-Hugo
      run: hugo --gc --minify
    - name: List public files
      run: ls public
    - name: Deploy-FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public